### ISSUE TITLE
alt attributes

### ISSUE THREAD

**Issue by gdedi001** [safuya/prj-rev-bwfs-dasmoto#3]
Make sure to add the `alt` attribute to your image tags
https://github.com/safuya/prj-rev-bwfs-dasmoto/blob/master/dasmotos/index.html#L14

https://www.w3schools.com/tags/att_img_alt.asp

**Comment by safuya** [comment]
Fixed in https://github.com/safuya/prj-rev-bwfs-dasmoto/commit/78875f080034a12a54d0aacb3c92203ebe25fa5c

I'm not sure if for the workflow in Github I'm meant to just close and comment?
